apiVersion: v1
kind: Pod
metadata:
  name: horfimbor-server-2
spec:
  containers:
    - name: hello
      image: localhost:32000/horfimbor-server-2
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 2000