language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - PROJECT=server
  - PROJECT=server2
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - .travis/build.sh
  - .travis/test.sh
