apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: lignee-server
    context: server
    docker:
      dockerfile: Dockerfile
  - image: lignee-server-2
    context: server2
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - server/k8s/pod.yml
    - server2/k8s/pod.yml
