[package]
name = "horfimbor"
version = "0.1.0"
authors = ["Aedius <aedius.filmania@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
cqrs-core = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"